### ISSUE TITLE
Colors on commands disappeared when upgrading to v3 of Discord4j

### ISSUE THREAD

**Issue by CorruptComputer** [CorruptComputer/Officer-Beepsky#4]
They all just need changed to have a Color set at the end of the `BotUtils.sendMessage()` method call. Green for command sucessful, red otherwise. Colors can already be found in the 8ball command.
- [x] HelpCommand #9
- [x] EightBallCommand
- [x] NameColorCommand #8 
- [x] QueueCommand #9
- [x] ListQueueCommand #9
- [x] SkipCommand #9
- [x] StopCommand #9
- [x] TimeSetCommand #9
- [x] VolumeCommand #9

**Comment by Jal20990** [comment]
Thank you

**Comment by santiagosuarezecheverri** [comment]
unable to access 'https://github.com/CorruptComputer/Officer-Beepsky.git/': The requested URL returned error: 403

**Comment by CorruptComputer** [comment]
@santiagosuarezecheverri Where was this error given?

**Comment by santiagosuarezecheverri** [comment]
If I want to upload the code, I do a push but I get that error

**Comment by CorruptComputer** [comment]
Oh, that is because you do not have push access to this repository. You'll have to create a fork of this, and push your changes there. After that you can do as fmmmle has done for #9 and create a pull request to this repository from your own. This issue has already been fixed in that PR, however if you would like to PR it still for learning and to get feedback I would be happy to review it as well!

**Comment by CorruptComputer** [comment]
Fixed via #9
